
test_that("model compiles and runs",{
  message("\nRecompiling and estimating model 20_8...\n")
  setwd('..')
  file.copy('../source/goa_pk.tpl', to='model_20_8/goa_pk.tpl', overwrite = TRUE)
  setwd('model_20_8')
  clean_pk_dir(full=TRUE)
  system("admb goa_pk", ignore.stdout = TRUE)
  expect_true(file.exists('goa_pk.exe'))
  system("goa_pk", ignore.stdout = TRUE)
  rep <- readLines('goa_pk.rep')
  clean_pk_dir()
  setwd('../testthat')
  ## saveRDS(rep,  "_expect_consistency_rep.rds")
  oldrep <- readRDS('_expect_consistency_rep.rds')
  expect_equal(rep, oldrep)
})
