# Executive Summary

Testing tables
\@ref(tab:catches)
\@ref(tab:incidental)
\@ref(tab:retained)
\@ref(tab:caa)
\@ref(tab:bycatch)
\@ref(tab:aged-fsh)
\@ref(tab:indices)
\@ref(tab:shelikof)
\@ref(tab:aged-srv2)
\@ref(tab:naa-srv2)
\@ref(tab:naa-srv1)
\@ref(tab:paa-srv3)
\@ref(tab:age-error)
\@ref(tab:natM)
\@ref(tab:naa-est)
\@ref(tab:waa-fsh)
\@ref(tab:waa-srv26)
\@ref(tab:waa-srv1)
\@ref(tab:selex)
\@ref(tab:timeseries)
\@ref(tab:rec-ssb)
\@ref(tab:spr-inputs)
\@ref(tab:model-history)
\@ref(tab:proj-scens)

Testing figures
Figures 1.\@ref(fig:catches-seas-by-area)

## Summary of Changes in Assessment Inputs

### Changes to input data
1. Fishery: 2021 total catch and catch at age.
2. Shelikof Strait acoustic survey: 2022 biomass index and age composition.
3. NMFS bottom trawl survey: 2021 age compositions
4. Summer acoustic survey: 2021 age compositions
5. ADF&G crab/groundfish trawl survey: 2022 biomass index 

### Changes in assessment methodology
Two minor changes were made to the model. First, a penalty of 1.3
was added to  recruitment deviations in all years. Previously
the penalty of 1.0 was applied only to early and late
deviations. Second, selectivity of the summer acoustic survey was
estimated. Previously this was assumed 1.0 for all ages. Together
these changes constitute model 19.1a.

## Summary of Results

The base model projection of female spawning biomass in `r year`
is `r ssb` t, which is `r 100*Finv(ssb)/Finv(b100)` % of unfished
spawning biomass (based on average post-1977 recruitment) and
above B40% (`r b40` t), thereby placing GOA pollock in sub-tier
“a” of Tier 3. New surveys in 2022 include the winter Shelikof
Strait acoustic survey and the ADF&G bottom trawl survey. Similar
to 2021 these showed similar trends, unlike previous years when
the surveys showed strongly contrasting trends. The risk matrix
table recommended by the SSC was used to determine whether to
recommend an ABC lower than the maximum permissible. The table is
applied by evaluating the severity of four types of
considerations that could be used to support a scientific
recommendation to reduce the ABC from the maximum
permissible. Although we identified some aspects of the stock
that merit close tracking, there were no elevated concerns about
stock assessment, population dynamics, environment/ecosystem, or
fisheries performance categories. We therefore recommend no
reduction from maximum permissible ABC.

The authors’ `r year+1` ABC recommendation for pollock in the
Gulf of Alaska west of 140° W lon. (W/C/WYK regions) is `r abc`
t, which is an increase of `r 100*(abcN-abcN.last)/abcN.last`
from the `r year-1` ABC. The author’s recommended `r year+2` ABC
is `r F(exec_table[12,4])` t. The OFL in `r year+1` is `r ofl` t,
and the OFL in `r year+2` if the ABC is taken in `r year+1` is 
`r F(exec_table[10,4])` t. These calculations are based on a
projected `r year` catch of `r F(tail(datfile$cattot,1))`
t. The estimated scale of the stock increased compared to
previous years, driven both by new data and model changes. 

For pollock in southeast Alaska (Southeast Outside region, east
of 140° W lon.), the ABC recommendation for both `r year+1` and
`r year+2` is 11,363 t (see Appendix 1B) and the OFL
recommendation for both `r year+1` and `r year +2` is 15,150 t. These
recommendations are based on a Tier 5 assessment using the
projected biomass in 2022 and 2023 from a random effects model
fit to the 1990-2021 bottom trawl survey biomass estimates of the
assessment area. 


```{r, child= "01a-main_table.Rmd", eval = T}

```


<!-- Text table of area apportionments (if any) for the recommended one- and two-year ahead ABCs and OFLs, with a brief description of the apportionment methodology. -->

<!-- ```{r, child= "01b-apportionment.Rmd", eval = T} -->

<!-- ``` -->


<!-- If so are so kind as to provide tables for the plan team, place them here -->

<!-- ```{r, child= "01c-plan_team.Rmd", eval = T} -->

<!-- ``` -->


