# Introduction


## Biology and Distribution

Walleye pollock (*Gadus chalcogrammus*; hereafter referred to as
pollock) is a semi-pelagic schooling fish widely distributed in
the North Pacific Ocean. Pollock in the central and western Gulf
of Alaska (GOA) are managed as a single stock independently of
pollock in the Bering Sea and Aleutian Islands. The separation of
pollock in Alaskan waters into eastern Bering Sea and Gulf of
Alaska stocks is supported by analysis of larval drift patterns
from spawning locations [@bailey1997a], genetic studies of
allozyme frequencies [@grant1980], mtDNA variability
[@mulligan1992a], and microsatellite allele variability
[@baily1997a]. 

## Stock Structure


The results of studies of stock structure within the Gulf of
Alaska are equivocal. There is evidence from allozyme frequency
and mtDNA that spawning populations in the northern part of the
Gulf of Alaska (Prince William Sound and Middleton Island) may be
genetically distinct from the Shelikof Strait spawning population
[@olsen2002]. However, significant variation in allozyme
frequency was found between Prince William Sound samples in 1997
and 1998, indicating a lack of stability in genetic structure for
this spawning population. @olsen2002 suggest that interannual
genetic variation may be due to variable reproductive success,
adult philopatry, source-sink population structure, or
utilization of the same spawning areas by genetically distinct
stocks with different spawning timing. There are important recent
preliminary results from a genetic analysis of 617 walleye
pollock from Japan, Bering Sea, Chukchi Sea, Aleutian Islands,
Alaska Peninsula, and Gulf of Alaska using low-coverage whole
genome sequencing. Results suggests there is a temporally stable
stock structure with a latitudinal gradient, i.e., Bering Sea
pollock are distinguishable from those in the Gulf of Alaska and
Aleutian Islands (I. Spies, personal communication, 2021). An
evaluation of stock structure for Gulf of Alaska pollock
following the template developed by NPFMC stock structure working
group was provided as an appendix to the 2012 assessment
[@dorn2012]. Available information supported the current approach
of assessing and managing pollock in the eastern portion of the
Gulf of Alaska (Southeast Outside) separately from pollock in the
central and western portions of the Gulf of Alaska
(Central/Western/West Yakutat). The main part of this assessment
deals only with the C/W/WYK stock, while results for a tier 5
assessment for southeast outside pollock are reported in Appendix
1B.

