# Results
## Model selection and evaluation
### Model selection
Prior to identifying a model for consideration, an analysis was
conducted of the impact of each new data element on model
results. Figure 1.\@ref(fig:add-data) shows the changes in
estimated spawning biomass as the updated catch projections,
catch at age, and surveys were added sequentially. This year,
additions changed both the trend and scale of the stock. In
particular adding the NMFS BT index and lengths, the Shelikof
index and ages, and summer acoustic index all substantially
increased the estimate of stock size. Such changes are not
typical, but given the large increases in survey indices it is
not entirely surprising that recent trends shifted upward.
Likewise, a change in scale is expected given the known
sensitivity for this model to changes in data and model
assumptions (as explored more thoroughly in e.g., @monnahan2021a)
and the Plan Team presentations in 2022 ([link to
pdf](https://meetings.npfmc.org/CommentReview/DownloadFile?p=7df129bb-16cb-4dba-a4d5-a160c31d087e.pdf&fileName=GOA%20pollock%20model%20updates.pdf)).


The intent of this year's assessment was to migrate to the new
TMB modeling framework without considering any changes to the
model structure. Conversion requires a substantial effort not
only in rewriting the C++ model, but also the workflow for
processing model inputs and results. After adding new data to
model 23.0, a final turning step was done using the @francis2011a
approach which reweighted all composition components, including
the summer acoustic age composition for the second time,
resulting in the only downward estimate of SSB in the model
results (Fig. 1.\@ref(fig:add-data)).

### Model evaluation
The fit of model 23.0 to age composition data was evaluated using
plots of observed and predicted age composition and residual
plots. Figure 1.\@ref(fig:tv-q) shows the estimates of
time-varying catchability for the Shelikof Strait acoustic survey
and the ADF&G crab/groundfish survey, as well as the constant
catchabilities for the other surveys. The catchability for the
Shelikof Strait acoustic survey continued to decrease away from
1, and is close to 0.5 in 2023. Catchability for the NMFS bottom
trawl and summer acoustic surveys were similar (0.80 and 0.70
respectively), while the age-1 and age-2 Shelikof survey
catchabilities were 0.22 and 0.26, respectively, reflecting the
fact that the survey does not target these immature ages. 

One-step-ahead (OSA) residuals are used this year to assess fits
to composition data [@trijoulet2023a]. Plots show the fit to
fishery age composition (Figs. 1.\@ref(fig:obs-exp-fsh),
1.\@ref(fig:osa-fsh)), Shelikof Strait acoustic survey age
composition
(Figs. 1.\@ref(fig:obs-exp-srv1),1.\@ref(fig:osa-srv1)), NMFS
trawl survey age composition
(Fig. 1.\@ref(fig:obs-exp-osa-srv2)), ADF&G trawl survey age
composition (Fig. 1.\@ref(fig:obs-exp-osa-srv3)) and the
summer acoustic survey
(Fig. 1.\@ref(fig:obs-exp-osa-srv6)). Model fits to fishery age
composition data are adequate in most years, though the very
strong 2012 year class shows up as a positive residual in
2016-2023 due to stronger than expected abundance in the age
composition. Previous assessments had strong patterns of negative
residuals for older ages, but it is clear now using OSA residuals
that these were not real and instead an artifact of Pearson
residuals being wrong. In contrast, the pattern of negative
residuals for age 4 and positive for age 3 persists with OSA
residuals, suggesting these are real. More complicated
selectivity forms were able to eliminate this pattern (Appendix
1F). The NMFS bottom trawl survey has relatively good residuals,
even for the most recent years where there is a misfit in the
index. The ADF&G compositions overall do not fit well, exhibiting
strong patterns of positive residuals after 2000.  The two
acoustic surveys had no apparent issues fitting to the
data. Overall there were no major issues in fitting the age
composition data and the issues highlighted here are considered
minor.

In recent assessments there was apparent conflict and uncertainty
in the data about the size of the 2018 cohort. The new estimate
of the initial cohort size is about 8 billion fish, larger than
average (Table 1.\@ref(tab:timeseries)), an increase from 5.4
billion in the previous assessment. This appears to confirm that
this cohort was relatively large and for unknown reasons was not
apparent in previous years of data.

Model fits to survey biomass estimates are reasonably good for
all surveys except the period 2015-2019 and now in 2023 with poor
fits to the 2023 Shelikof winter acoustic survey and NMFS bottom
trawl surveys (Fig. 1.\@ref(fig:index-fits)). The lack of fit in
the NMFS bottom trawl survey from 2015 to 2023 is a major concern
and discussed in the context of the risk table below. In
addition, the model is unable to fit the extremely low values for
the ADF&G survey in 2015-2017. The fit to the summer acoustic
survey is reasonable even during the most recent period. The
model shows good fits to both the 2021 Shelikof Strait acoustic
survey and the 2021 NMFS bottom trawl, while the 2021 ADF&G
bottom trawl and 2021 summer acoustic survey fits were
reasonable. The fit to the age-1 and age-2 Shelikof acoustic
indices was considered acceptable with a few exceptions
(Fig. 1.\@ref(fig:index-fits2)).

## Time series results
Parameter estimates and model output are presented in a series of
tables and figures. Estimated survey and fishery selectivity for
different periods are given in Table 1.\@ref(tab:selex) (see also
Figs. 1.\@ref(fig:fig-selex) and 1.\@ref(fig:selex-tv-fsh). Table
1.\@ref(tab:naa-est) gives the estimated population numbers at
age for the years 1970-`r year`. Table 1.\@ref(tab:timeseries)
gives the estimated time series of age 3+ population biomass,
age-1 recruitment, status, and harvest rate (catch/3+ biomass)
for 1977-`r year` (see also
Fig. 1.\@ref(fig:ssb-status-rec)). Table 1.\@ref(tab:rec-ssb)
gives coefficients of variation and 95% confidence intervals for
age-1 recruitment and spawning stock biomass. 

<!-- getting this from figures workbook sheet fig33 still need to -->
<!-- move it into R and pull in here-->
Stock size peaked in the early 1980s at approximately 103% of the
proxy for unfished stock size (B100% = mean 1978- `r year-1`
recruitment multiplied by the spawning biomass per recruit in the
absence of fishing (SPR at F=0), see below for how this is
calculated). In 2002, the stock dropped below B40% for the first
time since the early 1980s, and reached a minimum in 2003 of 35%
of unfished stock size. Over the years 2009-2013 stock size
showed a strong upward trend, increasing from 45% to 88% of
unfished stock size, but declined to 65% of unfished stock size
in 2015. The spawning stock peaked in 2017 at 90% as the strong
2012 year class matured, and has declined subsequently to 68%
in 2023. Figure 1.\@ref(fig:status) shows the historical pattern
of exploitation of the stock both as a time series of SPR and
fishing mortality compared to the current estimates of biomass
and fishing mortality reference points. Except from the mid-1970s
to mid-1980s fishing mortalities have generally been lower than
the current OFL definition, and in nearly all years were lower
than the FMSY proxy of F35%.

## Comparison of historical assessment results

A comparison of assessment results for the years 1999-`r year`
indicates the current estimated trend in spawning biomass for
1990-`r year` is consistent with previous estimates (Table
1.\@ref(tab:model-history) and Fig. 1.\@ref(fig:historical)). All
time series show a similar pattern of decreasing spawning biomass
in the 1990s, a period of greater stability in 2000s, followed by
an increase starting in 2008. The estimated `r year` age
composition from the current assessment was very similar to the
projected `r year` age composition from the `r year-1` assessment
(Fig. 1.\@ref(fig:pred-endN)). Generally, the two models agree
except for the age 1 recruits, where the `r year-1` model assumed
average recruitment, but the `r year` model has data from the
Shelikof survey which showed a weak 2022 year class. This difference
does not strongly affect the OFL and ABC for next year because
these fish are not in the exploitable population.

## Retrospective analysis of base model
A retrospective analysis consists of dropping the data
year-by-year from the current model, and provides an evaluation
of the stability of the current model as new data are
added. Figure 1.\@ref(fig:retros) shows a retrospective plot with
data sequentially removed back to `r year-7`. The range of errors
in the estimates of spawning biomass (if the current assessment
is accepted as truth) is -37.7% to -24.8%, but usually the errors
are much smaller (median absolute error is -33%). There is a
relatively large negative retrospective pattern in the assessment
(i.e., the model consistently underestimates SSB), and the
revised Mohn’s $\rho$ [@mohn1999a] across all seven peels for
terminal spawning biomass is -0.308. This is considered a
significant $\rho$ based on a bootstrapping analysis done on the
2022 assessment which found that by chance $\rho$ would be
between -0.21 and 0.29 (Bryan and Monnahan in prep), and is worse
than in recent years. Trends in estimates of cohort sizes is also
given in Fig. 1.\@ref(fig:retro-recruits).


## Stock productivity

Recruitment of GOA pollock is more variable (CV = `r CVrec`
over 1978-`r year-1`) than Eastern Bering Sea pollock (CV =
0.60). Other North Pacific groundfish stocks, such as sablefish
and Pacific ocean perch, also have high recruitment
variability. However, unlike sablefish and Pacific ocean perch,
pollock have a short generation time (~8 years), so that large
year classes do not persist in the population long enough to have
a buffering effect on population variability. Because of these
intrinsic population characteristics, the typical pattern of
biomass variability for GOA pollock will be sharp increases due
to strong recruitment, followed by periods of gradual decline
until the next strong year class recruits to the population. GOA
pollock is more likely to show this pattern than other groundfish
stocks in the North Pacific due to the combination of a short
generation time and high recruitment variability.

Since 1980, strong year classes have occurred periodically every
four to six years (Fig. 1.\@ref(fig:ssb-status-rec)). Because of
high recruitment variability, the mean relationship between
spawning biomass and recruitment is difficult to estimate despite
good contrast in spawning biomass. Strong and weak year classes
have been produced at high and low level of spawning
biomass. Spawner productivity is higher on average at low
spawning biomass compared to high spawning biomass, indicating
that survival of eggs to recruitment is density-dependent
(Fig. 1.\@ref(fig:spawn-prod)). However, this pattern of
density-dependent survival only emerges on a decadal scale, and
could be confounded with environmental variability on the same
temporal scale. The decadal trends in spawner productivity have
produced the pattern of increase and decline in the GOA pollock
population. The last two decades have been a period of relatively
low spawner productivity, though there appears to be a recent
increase. Age-1 recruitment in 2022 and 2023 is estimated to be
to be very weak, but the 2021 recruitment is above average,
although these estimates will remain very uncertain until
additional data become available (Figure
1.\@ref(fig:ssb-status-rec)).
