
### Risk Table and ABC Recommendation
The SSC in its December 2018 minutes recommended that all
assessment authors use the risk table when determining whether to
recommend an ABC lower than the maximum permissible.  The
Introduction to the Gulf of Alaska SAFE contains details on how
the risk table is implemented.

#### Assessment considerations

Several important assessment considerations arose in 2023 which
are revisited here in light of new data and models. In 2023 the new
abundance indices had conflict, with two going up and two going
down. The two surveys which cover the whole extent of the Gulf
were both up more than 70% from three years ago, while the two
with more limited spatial coverage were down from 2022. Not
surprisingly the model was not able to fit these data points, and
in particular the NMFS bottom trawl index has not fit well since
2015 (Fig. 1.\@ref(fig:index-fits)). Two surveys were completed
in 2024. The Shelikof index was higher, but lower than predicted,
similar to 2023. The ADF&G index was comparable to 2023. No new
models were able to resolve this conflict, and it remains a
concern.

The Shelikof abundance estimate is unexpectedly low and comprised
predominantly of pollock greater than 40 cm, but also coincides
with increased estimates of biomass in outlying areas, like the
Chirikof shelf break, relative to recent
years (Fig. 1.\@ref(fig:biomass-area-srv1)). However, biomass
estimates in the outlying areas are not abnormally high compared
to historical surveys and the Shelikof estimate still constitutes
the largest winter spawning area by far. This low Shelikof
estimate is thus not well explained by spatial shifts. A mismatch
between spawn timing and survey timing is another reasonable
hypothesis, but inclusion of this covariate into model 23b did
not resolve it. In the end, the fit is poor but not unprecedented
with this stock, and the previous few years have fit very well.
We therefore believe there is no reason for a substantial
concern.

In contrast, the NMFS bottom trawl survey has fit poorly for the
last 4 out of 5 biennial surveys. The expected trend is the
opposite of the observed trend in some years. The consistency of
this misfit is a larger concern, particularly because the prior
on catchability for this index is an important contributor to
estimating the scale of the stock. We therefore consider this an
elevated stock assessment concern.

Previous assessments had significant retrospective patterns, but
they were improved this year and not a concern.

Although there are poor model fits to some biomass indices, they
do not equate to a major concern. We therefore assign level 1:
normal for assessment considerations.

#### Population dynamics considerations

The large 2012 year class has had a strong impact on the recent
pollock population, from a steep decline in age diversity
(Fig. 1.\@ref(fig:fsh-chars)) to abnormal growth and maturation
(but not mortality as previously suspected), which had led to an
increase in concern. The estimated size of this cohort has
increased substantially over the last few years, including a 9.2%
and 9.9% increase in 2022 and 2023 with additional data, an
increase of almost 10 billion fish from 2020 to 2023. For
context, this increase alone would be considered a large cohort,
and only magnifies the already large impact it has on the population
dynamics over the last 10 years. However, the 2012 cohort,
now in the 10+ age class, is no longer the predominant one in the
fishery and three large ones (2017, 2018, and 2020) have already
entered the fishery (Figs. 1.\@ref(fig:ages-fsh) and
1.\@ref(fig:ssb-status-rec)), resulting in a return to normal age
diversity and population dynamics (Fig. 1.\@ref(fig:fsh-chars)).

The 2023 assessment highlighted a new phenomenon of concern,
specifically vanishingly small recent cohort estimates. This
issue was identified and resolved in model 23c and thus is no
longer a concern here.

#### Environmental/Ecosystem considerations
The most recent data available suggest an ecosystem risk Level 1
– Normal: “No apparent environmental/ecosystem concerns.” This
score is informed by ocean temperatures within optimal ranges for
pollock life stages, average to above average prey abundance,
reduced levels of competition, and moderate levels of predation.
Appendix 1A [@Shotwell2024] provides a detailed look at
environmental/ecosystem considerations specific to this stock
within the ecosystem and socioeconomic profile (ESP). Broad-scale
information on environmental and ecosystem considerations are
provided by the Gulf of Alaska Ecosystem Status Report
[@Ferriss2024]. The text below summarizes ecosystem information
related to GOA pollock provided from both the ESP and GOA ESR.

**Environmental Processes**: 
The 2023 ocean temperatures are all within known
optimal ranges for pollock life history stages (Feb-May 150-300m:
spawning 1-7°C, Mar-Apr 0-200m: egg 5-6°C, Apr-Jul surface: larva
3-7°C, as referenced in the ESP, Appendix 1A). The 2023/2024 El
Niño event brought warmer surface temperatures to the GOA in the
winter, but it was moderate and short-lived, resulting in
approximately average surface temperatures by spring in the
western GOA and continued warm surface waters through the spring
in the eastern GOA. Despite warmer than average surface
temperatures averaged across the western GOA shelf in January
(5.1°C, satellite-derived; @Lemagie2024a), NOAA’s January acoustic
survey in Shelikof Str. (key spawning habitat and time) observed
cooler temperatures in the top 10m (3.2°C) and showed no evidence
of warmth at depth (4°C at 100m; @Jones2024). Surface waters in
the western GOA cooled to approximately average temperatures in
March, and remained average through early spring and fall with
warmer waters in the summer (Satellite: @Lemagie2024a; Appendix
1A: Callahan, Seward Line: @Danielson2024). The central GOA
experienced no marine heatwave events this year, a decrease from
last year (Appendix 1A: Barbeaux). The north/south component of
the spring wind direction was toward the west during spring 2024
suggesting neutral retention in suitable larval habitat (Appendix
1A: Rogers). Upcoming 2025 winter and spring surface temperatures
are predicted to be cooler than average, din alignment with weak
La Nina condition [@Lemagie2024b].

**Prey**: 
Zooplankton biomass, primary prey for adult and juvenile pollock,
was average to above average on the GOA shelf in the spring and
summer. Spring zooplankton biomass along the central GOA Seward
Line included above average euphausiids, below average large
copepods, and average small copepods [@Hopcroft2024].
Planktivorous seabird reproductive success, an indicator of
zooplankton availability and nutritional quality, was generally
above average and increased from 2023 [@Drummond2024;@Whelan2024,
Appendix 1A: Zador]. Catches of YOY pollock in the summer beach
seine survey was the highest on record (Kodiak beach seine
survey, Appendix 1A: Laurel), suggesting productive feeding
conditions in the nearshore for larval pollock. Adult and
juvenile fish conditions were below average but slightly improved
from 2023 (winter acoustic survey, Appendix 1A: Monnahan). GOA
forage fish prey base was average to above average in 2024
(similar to 2023). Capelin continues to rebound in the GOA
[@McGowan2024;@Arimitsu2024], and herring continue to have
relatively elevated populations supported by the strong 2016 and
2020 year classes [@Hebert2024]. Forage species that are
relatively lower in abundance include eulachon, sandlance, and
juvenile salmon. The reproductive success of piscivorous, diving
seabirds (with an overlapping prey base with juvenile sablefish),
was generally above average across the GOA [@Drummond2024;@Whelan2024].

**Predators and Competitors**: 
Predation pressure from key groundfish species (arrowtooth
flounder, Pacific cod, Pacific halibut, and potentially
sablefish) is expected to be moderate. Pollock biomass consumed
by predators in the multispecies model (Pacific cod, Pacific
halibut, pollock, and arrowtooth flounder) remains low similar to
2023 (Appendix 1A: Adams). The sablefish population has had
multiple large age classes, 2022 potentially being the most
recent, potentially adding predation pressure to pollock prior to
moving to adult slope habitat (@Goethel2024; Appendix
1A). Western GOA Steller sea lions were not reassessed in
2023/2024 but remain lower than previous biomass peaks (K.
Sweeney, 2022). Potential competitors include relatively low
returns of pink salmon [@Whitehouse2024;@Vulstek2024], a
relatively large population of Pacific ocean perch (assessment,
@hulson2023a, Appendix 1A), and large year classes of juvenile
sablefish (assessment, @Goethel2024, Appendix 1A).

#### Fishery performance
Trends in effort-weighted fishery CPUE were examined in the ESP
(Appendix 1A) for two seasons, the `r year` pre-spawning fishery
(first trimester; A season) and the `r year-1` summer/fall
fishery (third trimeseter; B season). Fishery CPUE is above (A)
or close to (B) the long-term average, and is very consistent
with the abundance trend of exploitable biomass from the
assessment.

The fishery in the central Gulf (620 and 630) was closed on
September 25, 2024 due to exceedence of king salmon bycatch. This
is the first closure since it was put in place in 2010, and
consequently about 50 kt of pollock TAC were left, reducing the
expected catch in 2024. The estimated 2024 catch includes this
closure, and thus is in the model. So while abnormal and
noteworthy, the closure does not affect the risk of overfishing
and thus is not considered in the risk table.

No concerns regarding fishery performance were
identified and this element was given a score of 1.

#### Summary and ABC recommendation

```{r}
l1 = "Level 1: Normal"
l2 = "Level 2: Increased concern"
l3 = "Level 3: Extreme concern"

data.frame(assess = l1,
           pop = l1,
           enviro = l1,
           fish = l1) %>%
  flextable() %>%
    width(j = ~ assess, width = 1.5) %>%
    width(j = ~ pop, width = 1.5) %>%
    width(j = ~ enviro, width = 1.5) %>%
    width(j = ~ fish, width = 1.5) %>%
    set_header_labels(level = "",
                    assess = "Assessment-related considerations",
                    pop = "Population dynamics considerations",
                    enviro = "Ecosystem considerations",
                    fish = "Fishery Performance considerations related to the health of the stock") %>%
  fontsize(size = 10) %>%
  font(fontname = "Times", part = "all") %>%
  italic(part = "header")
```

Given the overall lack of elevated scores in the risk table, the
author’s recommended ABC is based on the maximum permissible ABC,
resulting in a `r year+1` ABC of `r maxabc` t, which is a 
`r pct.abc.changeF`from the `r year` ABC. The author’s recommended
`r year+2` ABC is `r F(exec_table[12,4])` t. The OFL in 
`r year+1` is `r ofl` t, and the OFL in `r year+2` if the `r year+1`
ABC is taken in `r year+1` is `r F(exec_table[10,4])` t.  

To evaluate the probability that the stock will drop below the
B20% threshold, we projected the stock forward for five years
using the author’s recommended fishing mortality schedule. This
projection incorporates uncertainty in stock status, uncertainty
in the estimate of B20%, and variability in future
recruitment. We then sampled from the probability of future
spawning biomass using Markov chain Monte Carlo (MCMC) using the
no-U-turn sampler available in TMB [@monnahan2018a]. Analysis of
the posterior samples indicated convergence (ESS>400 and Rhat
<1.01) and indicates that probability of the stock dropping
below B20% will be negligible through `r year+5`, conditional
upon the model specified here.
