
# Figures


```{r catches-sources, fig.cap="Overview of historical catches by source compared to the ABC/TAC"}
addfig('catches-source.png')
```

<br>

```{r catches-map, eval=TRUE, fig.cap=paste0("Distribution of pollock catch in the ", year-1, " fishery shown for 1/2 degree latitude by 1 degree longitude blocks by season in the Gulf of Alaska as determined by fishery observer-recorded haul retrieval locations. Blocks with less than 1.0 t of pollock catch are not shown. The area of the circle is proportional to the catch.")} 
 addfig('catches_map.png')
```

<br>

``` {r catches-seas-by-area, fig.cap=paste0("Distribution of pollock catch at age in the ", year-1, " separated by season and area."), eval = TRUE} 
 addfig('catches_seas_by_area.png')
```

<br>

``` {r data-overview, fig.cap="Overview of data sources and their relative weights. Circle sizes are relative to catches or data information for surveys within a row. Length compositions are only used in years without age compositions."}
addfig('data-overview.png')
```

<br>

```{r ages-fsh, eval=TRUE, fig.cap=paste("GOA pollock fishery age composition (1975-",year-1, ").The area of the circle is proportional to the catch. Diagonal lines show strong year classes.")}
 addfig("ages_fsh.png")
```

<br>

```{r map-BT-cpue, eval=TRUE, out.width="75%", fig.cap="Pollock catch per unit effort (CPUE) for the last three NMFS bottom trawl survey in the Gulf of Alaska. Used with permission from the Design-Based Production Data (NOAA Fisheries Alaska Fisheries Science Center, Groundfish Assessment Program, 2024). Accessed through the Alaska Fisheries Information Network https://github.com/MattCallahan-NOAA/gapproductssynopsis/"}
addfig("map_BT_cpue.png")
```

\newpage

<!-- <!-- alternate lenghts and ages depending on year --> 
<!-- ```{r lengths-area-srv2, eval=TRUE, fig.cap=paste0("Length composition of pollock by statistical area for the ", tail(datfile$srvyrs2,1)," NMFS bottom trawl survey.")} -->
<!--  addfig("lengths_area_srv2.png") -->
<!-- ``` -->

<!-- ```{r ages-area-srv2, eval=TRUE, fig.cap=paste0("Length composition of pollock by statistical area for the", tail(datfile$srv_acyrs2,1)," NMFS bottom trawl survey.")}
 addfig("ages_area_srv2.png") -->
<!--``` -->


```{r biomass-area-srv1, eval=TRUE, fig.cap="Biomass (age 1+) trends from winter acoustic surveys of pre-spawning aggregations of pollock in the GOA. Panel (a) shows estiamtes in natural space to highlight absolute scale and (b) in log space to better see trends across all areas."}
 addfig("biomass_area_srv1.png")
```

<br>

```{r ages-srv1, eval=TRUE, fig.cap=paste0("Estimated abundance at age in the Shelikof Strait acoustic survey (1981-", tail(datfile$srv_acyrs1,1)," except 1982, 1987, 1999, and 2011).  The area of the circle is proportional to the estimated abundance.")}
 addfig("ages_srv1.png")
```

<!-- ```{r summer-at-lcomps, eval=TRUE, fig.cap=paste0("Length composition of pollock by survey area for the ",year, " summer acoustic survey.")} -->
<!-- addfig("summer_at_lcomps.png") -->
<!-- ``` -->

```{r adfg-map, eval=TRUE, fig.cap=paste0("Tow locations for the ",tail(datfile$srvyrs3,1)," ADF\\&G crab/groundfish trawl survey.")}
 addfig("adfg_map.png")
```

<br>

```{r adfg-index, eval=TRUE, fig.cap="Comparison of ADF\\&G crab/groundfish trawl area-swept indices with year indices for a delta GLM model with a gamma error assumption for the positive observations. Both time series have been scaled by their mean."}
 addfig("adfg_index.png")
```

<br>

```{r ages-srv3, eval=TRUE, fig.cap=paste0("Estimated proportions at age in the ADF\\&G crab/groundfish survey (2000-",tail(datfile$srv_acyrs3,1), ").  The area of the circle is proportional to the estimated abundance.")}
 addfig("ages_srv3.png")
```

<br>

```{r fig-indices, eval=TRUE, fig.cap="Relative trends in pollock biomass since 1990 for the Shelikof Strait acoustic survey, the NMFS bottom trawl survey, and the ADF\\&G crab/groundfish trawl survey.  Each survey biomass estimate is standardized to the average since 1990. Shelikof Strait acoustic surveys prior to 2008 were re-scaled to be comparable to the surveys conducted from 2008 onwards by the R/V Oscar Dyson."}
 addfig("indices.png")
```

<br>

```{r fsh-chars, eval=TRUE, fig.cap="GOA pollock fishery catch characteristics."}
 addfig("fsh_chars.png")
```

<br>

```{r BT-prior, eval=TRUE, fig.cap="Prior on bottom trawl catchability used in the base model, and the estimate and uncertainty from the base model."}
 addfig("BT_prior.png")
```

<br>

```{r fig-natM, eval=TRUE, fig.cap=paste0("Alternative estimates of age-specific natural mortality.  The scaled average was used in the stock assessment model. See table 1.\\@ref(tab:natM) for more information")}
addfig("natM.png")
```

<br>

```{r mat-all, eval=TRUE, fig.cap="Estimates of the proportion mature at age from weighted visual maturity data collected on winter acoustic surveys in the Gulf of Alaska for all years. Maturity for age-1 fish is assumed to be zero."}
 addfig("mat_all.png")
```

<br>

```{r mat-recent, eval=TRUE, fig.cap=paste0("Estimates of the proportion mature at age from weighted visual maturity data collected during ", year-4,"-",year, " winter acoustic surveys in the Gulf of Alaska and long-term average proportion mature at age (1983-", year,"). Maturity for age-1 fish is assumed to be zero.")}
 addfig("mat_recent.png")
```

<br>

```{r a50, eval=TRUE, fig.cap="Age at 50% mature (top) and length at 50% mature (bottom) from annual logistic regressions for female pollock from winter acoustic survey data in the Gulf of Alaska. Estimates since 2003 are weighted by local abundance."}
 addfig("a50.png")
```

<br>

```{r fig-waa-srv1, eval=TRUE, fig.cap="Estimated weight at age of GOA pollock (ages 2, 4, 6, 8, and 10) from Shelikof Strait acoustic surveys used in the assessment model. In 1999 and 2011, when the acoustic survey was not conducted, weights-at-age were interpolated from surveys in adjacent years."}
 addfig("waa_srv1.png")
```

<br>

```{r fig-waa-re, eval=TRUE, fig.cap=paste0("Comparison of fishery weight at age for ",year-1," with estimates from the random effects model last year and this year’ assessment (top panel). Random effects model estimates for ",year," used in the assessment model and for yield projections (bottom panel).")}
 addfig("waa_re.png")
```

<br>

```{r add-data, eval=TRUE, fig.cap="Changes in estimated spawning biomass as new data were added successively to last year's base model, ordered by row in the legend at the top. The lower panel shows recent years relative to last year's model."}
 addfig("add_data.png")
```

<br>

```{r ssb-cv-re, eval=TRUE, fig.cap="Changes in estimated spawning biomass and uncertainty for proposed models. The top panel shows SSB and the CV of SSB, while the bottom shows change relative to last year's model with this year's data. Note that models are cumulative in the order they appear in the legend."}
 addfig("ssb_cv_re.png")
```

<br>

```{r ess, eval=TRUE, fig.cap="Effective sample sizes for models 23c and 23d. The former uses Francis tuning and the latter is calculated from the Dirichlet-multinomial (DM) estimates of dispersion. Annual differences in input sample size were introduced in model 23a."}
 addfig("ess.png")
```

<br>

```{r recruit-compare, eval=TRUE, fig.cap="Estimates of recruitment in log space among select alternative models."}
 addfig("recruit_compare.png")
```

<br>

```{r jitter, eval=TRUE, fig.cap="Results of a jitter analysis where the model was restarted 100 times from parameters randomly perturbed 10% from the MLE. The change in marginal negative log likelihood (deltaNLL), log of maximum gradient, and terminal SSB are shown in rows."}
 addfig("jitter.png")
```

<br>

```{r selftest, eval=TRUE, fig.cap="Results of a self-test analysis where the model is refit to 100 simulated data sets. Relative error for the timeseries of recruitment and spawning biomass are shown."}
 addfig("selftest.png")
```

<br>

```{r profile-q2, eval=TRUE, fig.cap="Profile likelihood on catchability for the NMFS BT biomass index, which includes a prior. The thick black line shows the total and colors individual components, each with their minimum shown as a point. "}
 addfig("profile_q2.png")
```

<br>

```{r tv-q, eval=TRUE, fig.cap="Covariate-linked catchability for the Shelikof Strait acoustic survey, a time-varying estimate for the ADF\\&G crab/groundfish trawl survey, and constant catchability for the NMFS bottom trawl, and the summer NMFS acoustic survey, for the final model. Ribbons and lines represent the 95% CI"}
 addfig("tv_q.png")
```

<br>

```{r obs-exp-fsh, eval=TRUE, fig.cap="Observed and predicted fishery age composition for GOA pollock from the base model. Dashed blue lines are observations and solid red lines are model expectations."} 
 addfig("obs_exp_fsh.png")
```

<br>

```{r obs-exp-srv1, eval=TRUE, fig.cap="Observed and predicted Shelikof Strait acoustic survey age composition for GOA pollock from the base model. Dashed blue lines are observations and solid red lines are model expectations. Age 1 and 2 fish are modeled separately and excluded."}
 addfig("obs_exp_srv1.png")
```

<br>

```{r obs-exp-srv2, eval=TRUE, fig.cap="Observed and predicted NMFS bottom trawl age composition for GOA pollock from the base model (top). Dashed blue lines are observations and solid red lines are model expectations."}
 addfig("obs_exp_srv2.png")
```

<br>

```{r obs-exp-srv3, eval=TRUE, fig.cap="Observed and predicted ADF\\&G bottom trawl age composition for GOA pollock from the base model (top). Dashed blue lines are observations and solid red lines are model expectations."}
 addfig("obs_exp_srv3.png")
```

<br>

```{r obs-exp-srv6, eval=TRUE, fig.cap="Observed and predicted summer acoustic trawl age composition for GOA pollock from the base model (top). Dashed blue lines are observations and solid red lines are model expectations."}
 addfig("obs_exp_srv6.png")
```

<br>

```{r osa-all, eval=TRUE, fig.cap="One-step-ahead (OSA) residuals for age composition data. These residuals will be distributed iid standard normal, within and among years, under a correctly specified model and assuming that the last bin fits perfectly. When the absolute residuals are larger than 3 or there are clear correlations or other patterns across ages/years, then the assumption is likely violated and interpreted as model misfit. Bubble plots can be used to detect temporal misfit, QQ plots and SDNR for non-normality or other statistical issues, and aggregate fits consistent misfit by age."}
 addfig("osa_all.png")
```

<br>

```{r index-fits, eval=TRUE, fig.cap="Model predicted (line) and observed survey biomass (points and 95% confidence intervals) for the four surveys. The winter Shelikof survey (top panel) is only for ages 3+."}
 addfig("index_fits.png")
```

<!-- ```{r index-fits2, eval=TRUE, fig.cap="Model predicted (line) and observed survey biomass (points and 95% confidence intervals)  for the age 1 and age 2 winter Shelikof surveys. "} -->
<!--  addfig("index_fits2.png") -->
<!-- ``` -->

<br>

```{r fig-selex, eval=TRUE, fig.cap="Estimated selectivity at age (lines) and uncertainty (+/- 1 SE; ribbons) for the fishery and surveys. Uncertainty calculations are done in logit space then converted and hence are asymmetric."}
 addfig("selex_svys.png")
```

<br>

```{r selex-tv-fsh, eval=TRUE, fig.cap="Estimates of time-varying double-logistic fishery selectivity for GOA pollock for the base model. The selectivity is scaled so the maximum in each year is 1.0."}
 addfig("selex_tv_fsh.png")
```

<br>

```{r ssb-status-rec, eval=TRUE, fig.cap=paste0("Estimated time series of GOA pollock spawning biomass (top) and age 1 recruitment (bottom) for the base model, with horizontal line at the average from 1978-",year-1,". Vertical bars represent two standard deviations.  The B35% and B40% lines represent the current estimate of these benchmarks.")}
 addfig("ssb_status_rec.png")
```

<br>

```{r status, eval=TRUE, fig.cap="Annual fishing mortality as measured in percentage of unfished spawning biomass per recruit (top).  GOA pollock spawning biomass relative to the unfished level and fishing mortality relative to FMSY (bottom). The ratio of fishing mortality to FMSY is calculated using the estimated selectivity pattern in that year. Estimates of B100% spawning biomass are based on current estimates of maturity at age, weight at age, and mean recruitment.  Because these estimates change as new data become available, this figure can only be used in a general way to evaluate management performance relative to biomass and fishing mortality reference levels."}
 addfig("status.png")
```

<br>

```{r retros, eval=TRUE, fig.cap=paste0("Retrospective plot of spawning biomass, recruitment, and fishing effort for models using 10 peels for the ",year," base model.") }
 addfig("retros.png")
```

<br>

```{r retro-recruits, eval=TRUE, fig.cap=paste0("Estimates of cohort size (points) and uncertainty (95% confidence intervals) as years of data are added to the model from the retrospective analysis")}
 addfig("retro_recruits.png")
```

<br>

```{r historical, eval=TRUE, fig.cap=paste0("Estimated female spawning biomass for historical stock assessments conducted between 1999-",year,". Lines reprsent the estimate in the assessment year and point is the terminal estimate in that year.")} 
 addfig("historical.png")
```

<br>

```{r pred-endN, eval=TRUE,  fig.cap=paste0("The estimated age composition in ",year, " from the ",year-1," and ",year," assessments. The age-1 recruits have no information in the ", year-1," assessment and so are the average and hence not comparable")}
 addfig("pred_endN.png")
```

<br>

```{r spawn-prod, eval=TRUE, fig.cap="GOA pollock spawning productivity, log(R/SSB) with a five-year running average (top). Spawning productivity in relation to female spawning biomass (bottom).  The Ricker stock-recruit curve is linear in a plot of spawner productivity against spawning biomass."}
 addfig("spawn_prod.png")
```


<!-- ```{r depletion, eval=TRUE, fig.cap=paste0("Uncertainty in spawning biomass in ", year+1,"-", year+5," based on a posterior samples from MCMC from the joint likelihood for the base model where catch is set to the maximum permissible FABC. Shown are the percentage below the horizontal line at 20% for each year.")}  -->
<!--  addfig("depletion.png") -->
<!-- ``` -->

<br>

```{r fig-proj-scens, eval=TRUE, fig.cap="Projected mean spawning biomass and catches in 2022-2026 under different harvest rates."} 
 addfig("proj_scens.png")
```
